import Head from "next/head";
import { Roboto } from "next/font/google";
import dynamic from "next/dynamic";
import { Box, Stack } from "@mui/material";
import AppToolbar from "~/components/AppToolbar";
import MapActions from "~/components/MapActions";

const LeafletMap = dynamic(() => import("~/components/Map"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>ACE Test Tool for Tracks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack className={`${roboto.className}`} sx={{ height: "100vh" }}>
        <AppToolbar />
        <Box sx={{ flexGrow: 1 }}>
          <LeafletMap />
          <MapActions offset={16} />
        </Box>
      </Stack>
    </>
  );
}
