import { useEffect } from 'react';
import dynamic from 'next/dynamic';
import { Roboto } from 'next/font/google';
import Head from 'next/head';
import { Box, CircularProgress, Stack } from '@mui/material';

import AppToolbar from '~/components/AppToolbar';

const LeafletMap = dynamic(() => import('~/components/Map'), {
  ssr: false,
  loading: () => (
    <Box
      sx={{
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <CircularProgress />
    </Box>
  ),
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function Home() {
  useEffect(() => {
    console.log('Home page loaded');
  });

  return (
    <>
      <Head>
        <title>ACE Test Tool for Tracks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack className={`${roboto.className}`} sx={{ height: '100vh' }}>
        <AppToolbar />
        <Box sx={{ flexGrow: 1 }}>
          <LeafletMap />
        </Box>
      </Stack>
    </>
  );
}
