import dynamic from 'next/dynamic';
import { Roboto } from 'next/font/google';
import Head from 'next/head';
import { Box, CircularProgress, Stack } from '@mui/material';

import AppToolbar from '~/components/AppToolbar';
import { Panel, PanelGroup, PanelResizeHandle } from 'react-resizable-panels';
import { useState } from 'react';
import { Map } from 'leaflet';

const LeafletMap = dynamic(() => import('~/components/Map'), {
  ssr: false,
  loading: () => (
    <Box
      sx={{
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <CircularProgress />
    </Box>
  ),
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function Home() {
  const [map, setMap] = useState<Map | null>(null);

  // Continuously update the map size when split view is resized
  const onResize = () => {
    map && map.invalidateSize();
  };

  return (
    <>
      <Head>
        <title>ACE Test Tool for Tracks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack className={`${roboto.className}`} sx={{ height: '100vh' }}>
        <AppToolbar />
        <Box sx={{ flexGrow: 1 }}>
          <PanelGroup direction="horizontal">
            <Panel defaultSize={70} onResize={onResize}>
              <LeafletMap onLoad={setMap} />
            </Panel>
            <PanelResizeHandle style={{ width: '4px' }} />
            <Panel defaultSize={30} minSize={20} maxSize={40}>
              <Box sx={{ width: '100%', height: '100%', overflow: 'auto' }}>
                stuff
              </Box>
            </Panel>
          </PanelGroup>
        </Box>
      </Stack>
    </>
  );
}
